Encode CalConnect administrative documents/publications
CalConnect/cc-admin-documents pull request #17
Opened 2024-12-20 00:19 UTC by anermina

Work in progress.

As requested in https://github.com/CalConnect/cc-admin-documents/issues/15.

CC: @ronaldtse

2024-12-30 10:32 UTC, ronaldtse requested changes

2024-12-30 10:32 UTC, ronaldtse commented on sources/cc-report-ioptestevent-9.adoc
> +:data-uri-image:
This is default behavior, we don’t need to set it.

2025-01-03 23:02 UTC, anermina commented on sources/cc-demo-0608.adoc
> +:copyright-holder: The Calendaring and Scheduling Consortium
Removed in https://github.com/CalConnect/cc-admin-documents/pull/17/commits/8b30ab125352c094d9e30a063951430744f22221.

2025-01-03 23:02 UTC, anermina commented on sources/cc-demo-0608.adoc
> +:toclevels: 1
Removed in https://github.com/CalConnect/cc-admin-documents/pull/17/commits/8b30ab125352c094d9e30a063951430744f22221.

2025-01-03 23:03 UTC, anermina commented on sources/cc-report-ioptestevent-9.adoc
> +:data-uri-image:
Removed in https://github.com/CalConnect/cc-admin-documents/pull/17/commits/8b30ab125352c094d9e30a063951430744f22221.

2025-01-07 06:02 UTC, ronaldtse commented on sources/cc-0812-pres-meet-cc/pres-bedework.adoc
> +** Director, Communications & Middleware Technologies, Rensselaer Polytechnic Institute
Should be one level list.

2025-01-07 23:11 UTC, anermina commented on sources/cc-0812-pres-meet-cc/pres-bedework.adoc
> +** Director, Communications & Middleware Technologies, Rensselaer Polytechnic Institute
This is resolved in https://github.com/CalConnect/cc-admin-documents/pull/17/commits/8c87f5fd8ff1ed9c5a5b45f0874728c4f6c4d91a.

2025-01-08 23:59 UTC, anermina commented on sources/cc-demo-0608.adoc
> +:imagesdir: images/demo-0608
This is applied in https://github.com/CalConnect/cc-admin-documents/pull/17/commits/07dbe5fff288bc31b9c19203878300e80c95fa02 and https://github.com/CalConnect/cc-admin-documents/commit/9ced4d33d771679a3f884fcaaf0987b901b97e13.

2025-01-12 23:43 UTC, anermina commented
@ronaldtse All the files from https://github.com/CalConnect/calconnect.org/tree/main/publications are encoded here. Several tickets and notes are related to these encodings, as described in the first comment to this PR. Please let me know if any changes are required. Thank you!

2025-01-24 09:10 UTC, ronaldtse commented
The site isn't building for some reason. I already aligned all the date formats. Let's merge this first and handle that build issue after.

2025-01-24 09:10 UTC, ronaldtse commented
Thank you @anermina ! That's a ton of documents!

2025-01-24 09:10 UTC, merged